'use client'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const queryClient = new QueryClient()

//export const metadata: Metadata = {
//  title: 'Create Next App',
//  description: 'Generated by create next app',
//}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <main className="flex w-fit mx-auto min-h-screen flex-col gap-[19px] p-24">
            {children}
          </main>
        </QueryClientProvider>
      </body>
    </html>
  )
}
